apiVersion: apps/v1
kind: Deployment
metadata:
  name: salary-prediction-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: salary-prediction
  template:
    metadata:
      labels:
        app: salary-prediction
    spec:
      containers:
      - name: salary-prediction
        image: salary-prediction:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
