apiVersion: v1
kind: Service
metadata:
  name: salary-prediction-service
spec:
  type: NodePort
  selector:
    app: salary-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
